### ISSUE TITLE
无法加载PclDLL

### ISSUE THREAD

**Issue by ninzhenyouxiu** [booksuper/PclCSharp#1]
我下载了代码直接打开Demo，加载文件的时候提示无法加载PclDLL.dll，所有的depend/×64下面的dll和你说的四个dll都在exe目录下

**Comment by booksuper** [comment]
能不能给我看下你的vs配置，我这是在win10、vs2017，.net4.6.1下封装的。你的配置也应该这样才行，还有记得生成平台一定得是x64

**Comment by booksuper** [comment]
> 我下载了代码直接打开Demo，加载文件的时候提示无法加载PclDLL.dll，所有的depend/×64下面的dll和你说的四个dll都在exe目录下
你先不用重新生成，直接运行我demo中的exe，看能不能运行，位置在\PclCSharp\demo\PclCSharpDemo\IoDemo\bin\x64\Debug\IoDemo.exe

**Comment by ninzhenyouxiu** [comment]
添加了少的dll文件，解决了

**Comment by ninzhenyouxiu** [comment]
经过博主远程指导，发现是少了vtk的相关dll，目前已解决

**Comment by booksuper** [comment]
经过排查，是因为io模块中增添了vtk的相关函数，但忘了将vtk的相关dll放进去，目前已经解决
