### ISSUE TITLE
是否支持修改点云的某一点值？

### ISSUE THREAD

**Issue by kywish** [booksuper/PclCSharp#4]
PointCloudXYZ.GetX、GetY、GeY可以取到某一点的值，是否支持SetX SetY...?

**Comment by booksuper** [comment]
目前没有这个功能，但可以添加，这个功能很简单。你是有这个需求？

**Comment by booksuper** [comment]
> PointCloudXYZ.GetX、GetY、GeY可以取到某一点的值，是否支持SetX SetY...?
在PointCloudXYZ类中增加了SetX、SetY 、SetZ函数，已通过测试。
如果觉得好用，可以给作者star和fork

**Comment by kywish** [comment]
> > PointCloudXYZ.GetX、GetY、GeY可以取到某一点的值，是否支持SetX SetY...?
> > 在PointCloudXYZ类中增加了SetX、SetY 、SetZ函数，已通过测试。
> > 如果觉得好用，可以给作者star和fork

Great！THX.
