### ISSUE TITLE
PclCSharp.Io.loadTxtFile 报错

### ISSUE THREAD

**Issue by mindcont** [booksuper/PclCSharp#8]
![输入图片说明](https://images.gitee.com/uploads/images/2022/0708/185147_6cd7e5a0_8350599.png "屏幕截图.png")

![输入图片说明](https://images.gitee.com/uploads/images/2022/0708/203339_97903f8f_8350599.png "屏幕截图.png")

测试时，txt文件下载
http://deershare.com/recv/156326  
快传密码：156326

```
有关调用实时(JIT)调试而不是此对话框的详细信息，
请参见此消息的结尾。

************** 异常文本 **************
System.Runtime.InteropServices.SEHException (0x80004005): 外部组件发生异常。
   在 PclCSharp.Io.loadTxtFile(String path, IntPtr pc)
   在 IoDemo.IoDemoForm.loadTxtButton_Click(Object sender, EventArgs e) 位置 E:\Dev\PCL\pcl-csharp\demo\PclCSharpDemo\IoDemo\IoDemoForm.cs:行号 296
   在 System.Windows.Forms.Control.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnClick(EventArgs e)
   在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   在 System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   在 System.Windows.Forms.Control.WndProc(Message& m)
   在 System.Windows.Forms.ButtonBase.WndProc(Message& m)
   在 System.Windows.Forms.Button.WndProc(Message& m)
   在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)


************** 已加载的程序集 **************
mscorlib
    程序集版本:4.0.0.0
    Win32 版本:4.8.4510.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
----------------------------------------
IoDemo
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/IoDemo.exe
----------------------------------------
System.Windows.Forms
    程序集版本:4.0.0.0
    Win32 版本:4.8.4488.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
----------------------------------------
System
    程序集版本:4.0.0.0
    Win32 版本:4.8.4488.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
----------------------------------------
System.Drawing
    程序集版本:4.0.0.0
    Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
----------------------------------------
PointCloudSharpDll
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/PointCloudSharpDll.DLL
----------------------------------------
Kitware.VTK
    程序集版本:5.8.0.607
    Win32 版本:5.8.0.607
    基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/Kitware.VTK.DLL
----------------------------------------
System.Configuration
    程序集版本:4.0.0.0
    Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
----------------------------------------
System.Core
    程序集版本:4.0.0.0
    Win32 版本:4.8.4470.0 built by: NET48REL1LAST_C
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
----------------------------------------
System.Xml
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
----------------------------------------
Kitware.mummy.Runtime
    程序集版本:1.0.2.599
    Win32 版本:1.0.2.599
    基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/Kitware.mummy.Runtime.DLL
----------------------------------------
PclCSharp
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/PclCSharp.DLL
----------------------------------------
mscorlib.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll
----------------------------------------
OptaneShellExt
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/OptaneShellExt.dll
----------------------------------------
SharpShell
    程序集版本:2.2.0.0
    Win32 版本:2.2.0.0
    基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/SharpShell.DLL
----------------------------------------
PinningServiceApi
    程序集版本:1.0.0.0
    Win32 版本:1.0.0.0
    基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/PinningServiceApi.DLL
----------------------------------------
System.ComponentModel.Composition
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll
----------------------------------------
System.Windows.Forms.resources
    程序集版本:4.0.0.0
    Win32 版本:4.8.4084.0 built by: NET48REL1
    基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll
----------------------------------------

************** JIT 调试 **************
要启用实时(JIT)调试，
该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置
jitDebugging 值。
编译应用程序时还必须启用
调试。

例如:

<configuration>
    <system.windows.forms jitDebugging="true" />
</configuration>

启用 JIT 调试后，任何未经处理的异常
都将被发送到在此计算机上注册的 JIT 调试程序，
而不是由此对话框处理。
```

**Comment by booksuper** [comment]
这个错误一般是因为你的TXT文件格式不对导致的。本函数对TXT文件格式有两个要求
第一，文件中只能包含数字。第二，每一行代表一个点的xyz数据，数字之间必须以空格隔开



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年8月30日(周二) 下午4:50
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [booksuper/PclCSharp] PclCSharp.Io.loadTxtFile 报错 (Issue #8)




 

 

 
测试时，txt文件下载
 http://deershare.com/recv/156326
 快传密码：156326
 有关调用实时(JIT)调试而不是此对话框的详细信息， 请参见此消息的结尾。 ************** 异常文本 ************** System.Runtime.InteropServices.SEHException (0x80004005): 外部组件发生异常。    在 PclCSharp.Io.loadTxtFile(String path, IntPtr pc)    在 IoDemo.IoDemoForm.loadTxtButton_Click(Object sender, EventArgs e) 位置 E:\Dev\PCL\pcl-csharp\demo\PclCSharpDemo\IoDemo\IoDemoForm.cs:行号 296    在 System.Windows.Forms.Control.OnClick(EventArgs e)    在 System.Windows.Forms.Button.OnClick(EventArgs e)    在 System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)    在 System.Windows.Forms.Control.WmMouseUp(Message&amp; m, MouseButtons button, Int32 clicks)    在 System.Windows.Forms.Control.WndProc(Message&amp; m)    在 System.Windows.Forms.ButtonBase.WndProc(Message&amp; m)    在 System.Windows.Forms.Button.WndProc(Message&amp; m)    在 System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam) ************** 已加载的程序集 ************** mscorlib     程序集版本:4.0.0.0     Win32 版本:4.8.4510.0 built by: NET48REL1LAST_B     基本代码:file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll ---------------------------------------- IoDemo     程序集版本:1.0.0.0     Win32 版本:1.0.0.0     基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/IoDemo.exe ---------------------------------------- System.Windows.Forms     程序集版本:4.0.0.0     Win32 版本:4.8.4488.0 built by: NET48REL1LAST_C     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll ---------------------------------------- System     程序集版本:4.0.0.0     Win32 版本:4.8.4488.0 built by: NET48REL1LAST_C     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll ---------------------------------------- System.Drawing     程序集版本:4.0.0.0     Win32 版本:4.8.4390.0 built by: NET48REL1LAST_C     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll ---------------------------------------- PointCloudSharpDll     程序集版本:1.0.0.0     Win32 版本:1.0.0.0     基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/PointCloudSharpDll.DLL ---------------------------------------- Kitware.VTK     程序集版本:5.8.0.607     Win32 版本:5.8.0.607     基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/Kitware.VTK.DLL ---------------------------------------- System.Configuration     程序集版本:4.0.0.0     Win32 版本:4.8.4190.0 built by: NET48REL1LAST_B     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll ---------------------------------------- System.Core     程序集版本:4.0.0.0     Win32 版本:4.8.4470.0 built by: NET48REL1LAST_C     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll ---------------------------------------- System.Xml     程序集版本:4.0.0.0     Win32 版本:4.8.4084.0 built by: NET48REL1     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll ---------------------------------------- Kitware.mummy.Runtime     程序集版本:1.0.2.599     Win32 版本:1.0.2.599     基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/Kitware.mummy.Runtime.DLL ---------------------------------------- PclCSharp     程序集版本:1.0.0.0     Win32 版本:1.0.0.0     基本代码:file:///E:/Dev/PCL/pcl-csharp/demo/PclCSharpDemo/IoDemo/bin/x64/Debug/PclCSharp.DLL ---------------------------------------- mscorlib.resources     程序集版本:4.0.0.0     Win32 版本:4.8.4084.0 built by: NET48REL1     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/mscorlib.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/mscorlib.resources.dll ---------------------------------------- OptaneShellExt     程序集版本:1.0.0.0     Win32 版本:1.0.0.0     基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/OptaneShellExt.dll ---------------------------------------- SharpShell     程序集版本:2.2.0.0     Win32 版本:2.2.0.0     基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/SharpShell.DLL ---------------------------------------- PinningServiceApi     程序集版本:1.0.0.0     Win32 版本:1.0.0.0     基本代码:file:///C:/Windows/System32/DriverStore/FileRepository/iastorpinningcomponent.inf_amd64_e59109c0b9bfb49c/PinningServiceApi.DLL ---------------------------------------- System.ComponentModel.Composition     程序集版本:4.0.0.0     Win32 版本:4.8.4084.0     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.ComponentModel.Composition/v4.0_4.0.0.0__b77a5c561934e089/System.ComponentModel.Composition.dll ---------------------------------------- System.Windows.Forms.resources     程序集版本:4.0.0.0     Win32 版本:4.8.4084.0 built by: NET48REL1     基本代码:file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms.resources/v4.0_4.0.0.0_zh-Hans_b77a5c561934e089/System.Windows.Forms.resources.dll ---------------------------------------- ************** JIT 调试 ************** 要启用实时(JIT)调试， 该应用程序或计算机的 .config 文件(machine.config)的 system.windows.forms 节中必须设置 jitDebugging 值。 编译应用程序时还必须启用 调试。 例如: <configuration&gt;     <system.windows.forms jitDebugging="true" /&gt; </configuration&gt; 启用 JIT 调试后，任何未经处理的异常 都将被发送到在此计算机上注册的 JIT 调试程序， 而不是由此对话框处理。

**Comment by mindcont** [comment]
感谢😊
