### ISSUE TITLE
可视化点云聚类结果

### ISSUE THREAD

**Issue by cat722** [booksuper/PclCSharp#9]
您好，基于您的库，我尝试了点云聚类，但是不知道怎么可视化聚类后的点云，请问能否提供一下帮助？非常感谢。

**Comment by booksuper** [comment]
我后续写一个分割的demo，这个demo里面会包含欧式聚类和区域生长等经典聚类算法的例子



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年9月22日(周四) 晚上8:51
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: [booksuper/PclCSharp] 可视化点云聚类结果 (Issue #9)




 
您好，基于您的库，我尝试了点云聚类，但是不知道怎么可视化聚类后的点云，请问能否提供一下帮助？非常感谢。

**Comment by cat722** [comment]
好的，非常感谢！另外我想问下您了解在C#下怎么给点云画Boundingbox吗？

**Comment by booksuper** [comment]
> 您好，基于您的库，我尝试了点云聚类，但是不知道怎么可视化聚类后的点云，请问能否提供一下帮助？非常感谢。

点云分割demo已更新
